export interface CountryOption {
  name: string;
  dial: string;
  defaultLang: string;
}

export const COUNTRIES: CountryOption[] = [
  { name: "India", dial: "+91", defaultLang: "हिन्दी" },
  { name: "Bangladesh", dial: "+880", defaultLang: "বাংলা" },
  { name: "United States", dial: "+1", defaultLang: "English (US)" },
  { name: "United Kingdom", dial: "+44", defaultLang: "English (UK)" },
  { name: "Canada", dial: "+1", defaultLang: "Français (Canada)" },
  { name: "Australia", dial: "+61", defaultLang: "English (UK)" },
  { name: "Germany", dial: "+49", defaultLang: "Deutsch" },
  { name: "France", dial: "+33", defaultLang: "Français (France)" },
  { name: "Spain", dial: "+34", defaultLang: "Español (España)" },
  { name: "Mexico", dial: "+52", defaultLang: "Español" },
  { name: "Brazil", dial: "+55", defaultLang: "Português (Brasil)" },
  { name: "Portugal", dial: "+351", defaultLang: "Português (Portugal)" },
  { name: "Italy", dial: "+39", defaultLang: "Italiano" },
  { name: "Japan", dial: "+81", defaultLang: "日本語" },
  { name: "South Korea", dial: "+82", defaultLang: "한국어" },
  { name: "China", dial: "+86", defaultLang: "中文(简体)" },
  { name: "Taiwan", dial: "+886", defaultLang: "中文(台灣)" },
  { name: "Hong Kong", dial: "+852", defaultLang: "中文(香港)" },
  { name: "Indonesia", dial: "+62", defaultLang: "Bahasa Indonesia" },
  { name: "Malaysia", dial: "+60", defaultLang: "Bahasa Melayu" },
  { name: "Philippines", dial: "+63", defaultLang: "Filipino" },
  { name: "Vietnam", dial: "+84", defaultLang: "Tiếng Việt" },
  { name: "Thailand", dial: "+66", defaultLang: "ภาษาไทย" },
  { name: "Turkey", dial: "+90", defaultLang: "Türkçe" },
  { name: "Russia", dial: "+7", defaultLang: "Русский" },
  { name: "Ukraine", dial: "+380", defaultLang: "Українська" },
  { name: "Poland", dial: "+48", defaultLang: "Polski" },
  { name: "Netherlands", dial: "+31", defaultLang: "Nederlands" },
  { name: "Sweden", dial: "+46", defaultLang: "Svenska" },
  { name: "Norway", dial: "+47", defaultLang: "Norsk (Bokmål)" },
  { name: "Denmark", dial: "+45", defaultLang: "Dansk" },
  { name: "Finland", dial: "+358", defaultLang: "Suomi" },
  { name: "Czech Republic", dial: "+420", defaultLang: "Čeština" },
  { name: "Hungary", dial: "+36", defaultLang: "Magyar" },
  { name: "Romania", dial: "+40", defaultLang: "Română" },
  { name: "Slovakia", dial: "+421", defaultLang: "Slovenčina" },
  { name: "Croatia", dial: "+385", defaultLang: "Hrvatski" },
  { name: "Serbia", dial: "+381", defaultLang: "Српски" },
  { name: "Greece", dial: "+30", defaultLang: "Ελληνικά" },
  { name: "Bulgaria", dial: "+359", defaultLang: "Български" },
  { name: "Saudi Arabia", dial: "+966", defaultLang: "العربية" },
  { name: "United Arab Emirates", dial: "+971", defaultLang: "العربية" },
  { name: "Egypt", dial: "+20", defaultLang: "العربية" },
  { name: "Israel", dial: "+972", defaultLang: "עברית" },
  { name: "Pakistan", dial: "+92", defaultLang: "English (US)" },
  { name: "Iran", dial: "+98", defaultLang: "فارسی" },
  { name: "South Africa", dial: "+27", defaultLang: "Afrikaans" },
  { name: "Singapore", dial: "+65", defaultLang: "English (US)" },
];
