const fs = require("fs");

const EN = {
  home: "Home",
  feels: "Feels",
  reels: "Reels",
  search: "Search",
  messages: "Chats",
  profile: "Profile",
  saved_posts: "Saved Posts",
  settings: "Settings",
  help_support: "Help & Support",
  help_and_support: "Help & Support",
  logout: "Log Out",
  create: "Create",
  insights: "Insights",
  notifications: "Notifications",
  no_notifications: "No new notifications",
  explore: "Explore",
  app_title: "Tweetgram",
  join_us: "Join Us",
  tagline: "Share what you're into with the people who get you.",
  get_started: "Get started",
  select_language: "Select Language",
  search_language: "Search language...",
  follow: "Follow",
  following: "Following",
  unfollow: "Unfollow",
  requested: "Requested",
  message: "Message",
  edit_profile: "Edit Profile",
  save: "Save",
  delete_account: "Delete Account",
  cancel: "Cancel",
  confirm: "Confirm",
  share: "Share",
  share_profile: "Share Profile",
  copy_link: "Copy Link",
  report: "Report",
  block: "Block",
  add_comment: "Add a comment...",
  comment: "Comment",
  comments: "Comments",
  likes: "Likes",
  views: "Views",
  reactions: "Reactions",
  love: "Love",
  original_audio: "Original Audio",
  posted: "Posted",
  no_posts: "No posts yet",
  no_saved: "No saved posts yet",
  view_all_comments: "View all comments",
  post: "Post",
  account: "Account",
  privacy: "Privacy",
  theme: "Theme",
  dark_mode: "Dark Mode",
  light_mode: "Light Mode",
  language: "Language",
  trending: "Trending",
  login: "Log In",
  log_in: "Log In",
  sign_up: "Sign Up",
  continue_google: "Continue with Google",
  continue_email: "Continue with Email",
  continue_with_google: "Continue with Google",
  continue_with_email: "Continue with Email",
  agree_terms: "I confirm I am at least 13 years old and I agree to the Terms of Service and Privacy Policy.",
  please_accept_terms: "Please accept the terms to continue",
  terms: "Terms of Service",
  privacy_policy: "Privacy Policy",
  terms_and_privacy: "Terms & Privacy",
  security: "Security",
  posts_tab: "Posts",
  reels_tab: "Reels",
  saved_tab: "Saved",
  tagged_tab: "Tagged",
  followers: "followers",
  following_count: "following",
  posts_count: "Posts",
  bio: "Bio",
  no_results: "No results found",
  search_placeholder: "Search accounts or tags...",
  friends: "friends",
  photos: "Photos",
  all_photos: "All photos",
  about: "About",
  change_cover: "Change Cover Photo",
  change_avatar: "Change Avatar",
  profile_overview: "Profile Overview",
  location: "Location",
  joined: "Joined",
  verified_creator: "Verified Creator",
  all: "All",
  food: "Food",
  essentials: "Essentials",
  blood: "Blood",
  remove_saved: "Remove from saved",
  download: "Download",
  downloading: "Downloading...",
  download_video: "Download video",
  copyright_report: "Copyright / Report",
  edit_video: "Edit video",
  delete_video: "Delete video",
  delete: "Delete",
  no_comments: "No comments yet. Start the conversation.",
  pinned_by_creator: "Pinned by creator",
  pin: "Pin",
  unpin: "Unpin",
  delete_account_request: "Delete Account Request",
  submit_request: "Submit Request",
  username: "Username",
  full_name: "Full Name",
  phone_number: "Mobile Phone Number",
  save_changes: "Save Changes",
  search_input_placeholder: "Search User | Video | Creator",
  no_content: "No content",
  create_new_content: "Create New Content",
  sharing: "Sharing...",
  write_caption: "Write a caption...",
  guidelines: "Guidelines, policies & creator eligibility",
  content_guidelines: "Content Guidelines",
  upload_guidelines: "Upload Guidelines",
  feature_eligibility: "Feature Eligibility",
  faqs: "Frequently Asked Questions",
  contact_support: "Contact Support Team",
  removed_from_saved: "Removed from saved",
  whats_on_your_mind: "What's on your mind?",
  create_story: "Create story",
  your_story: "Your story",
  create_post: "Create Post",
  photo_video: "Photo/video",
  feeling_activity: "Feeling/activity",
  add_to_your_post: "Add to your post",
  change_password_security: "Change Password / Security",
  two_factor_desc: "Two-factor authentication & password",
  name_bio_desc: "Name, bio, username & contact",
  saved_desc: "Saved collections and bookmarks",
  preferences: "Preferences",
  interface_lang_desc: "Interface and content language",
  toggle_appearance_desc: "Toggle dark & light appearance",
  creator_policies_desc: "Creator policies, guidelines & FAQs",
  community_terms_desc: "Community standards & terms",
  danger_zone: "Danger Zone",
  safety_standards: "Safety Standards",
  help_center_policies: "Help Center & Creator Policies",
  strict_adult_restrictions: "Strict Adult Content (18+) Restrictions",
  copyright_originality: "Copyright & Original Content",
  daily_video_limit: "Daily Video Limit",
  aspect_ratio: "Aspect Ratio & Resolution",
  my_gift_feature: "'My Gift' Monetization",
  tap_to_upload_avatar: "Tap to upload new profile avatar",
  tell_us_about_you: "Tell us about you",
  country_and_language: "Country & language",
  country: "Country",
  app_language: "App language",
  finish_setup: "Finish setup",
  continue: "Continue",
  back: "Back",
  add_your_photos: "Add your photos",
  header_banner: "Header Banner",
  name_phone_required: "Please enter your full name and mobile number",
  select_reason: "Please select a reason for account deletion."
};

module.exports = { EN };
